name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: go build ./...
    
    - name: test
      run: go test ./...
    
    - name: pull-deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd app
          git pull origin master
          go test -v ./..
          docker-compose down && docker-compose up --build -d --remove-orphans